repos:
# 1) 기본 안전장치
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
      files: ^parenting-helper-webapp/prompts/|^\.github/workflows/|^.*\.ya?ml$
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: detect-private-key
    - id: check-added-large-files
      args: ["--maxkb=512"]

# 2) 코드 품질
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black
      files: ^parenting-helper-webapp/.*\.py$
      args: ["--fast"]  # 빠른 모드 활성화

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      args: ["--fix", "--select", "I"]
      files: ^parenting-helper-webapp/.*\.py$
      stages: [commit]  # 커밋 시에만 실행
